// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfftjfvrzbbtrjkuzdwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmZnRqZnZyemJidHJqa3V6ZHdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTE3ODMsImV4cCI6MjA3MDEyNzc4M30.CRq8200xhr3uZelaFB3B1b0Y-EyDGbsKh5FulQovriA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});